# config.py
BROWSERS = {
    "chrome": {
        "driver_path": "/usr/local/bin/chromedriver",
        "binary_location": "/usr/bin/google-chrome"
    },
    "firefox": {
        "driver_path": "/usr/local/bin/geckodriver",
        "binary_location": "/usr/bin/firefox",
        "profile_path": "/home/osboxes/snap/firefox/common/.cache/mozilla/firefox/f4lfpmkf.default"  # Ajusta esto a tu ruta exacta

    },
    "brave": {
        "driver_path": "/usr/local/bin/chromedriver",
        "binary_location": "/usr/bin/brave-browser"
    },
    "edge": {
        "driver_path": "/usr/local/bin/msedgedriver",
        "binary_location": "/usr/bin/microsoft-edge"
    },
    #"tor": {
     #   "driver_path": "/usr/local/bin/geckodriver",
      #  "binary_location": "/home/osboxes/Downloads/tor-browser/Browser/firefox.real"
    #}
}

URLS = [
    "https://www.elmundo.es/",
    "https://elpais.com/",
    "https://www.filmaffinity.com/es/film750283.html?affid=100037",
    "https://www.google.com/maps/place/Churrasco+de+Oro/@42.0557709,-7.1504178,17z/data=!3m1!4b1!4m6!3m5!1s0xd3a8ba678dd9ac3:0xea58d2288bc84f1f!8m2!3d42.0557709!4d-7.1478429!16s%2Fg%2F1tj74x7k?entry=ttu",
    "https://www.marca.com/",
    "https://es.linkedin.com/pub/dir/Jorge/Contreras/es-0-Espa%C3%B1a",
    "https://www.instagram.com/azzaro.pub/?hl=es",
    "https://web.whatsapp.com/",
    "https://www.facebook.com/?locale=es_ES",
    "https://openai.com/chatgpt/",
    "https://www.youtube.com/watch?v=O5kvqVriJdk",
    "https://open.spotify.com/",
    "https://es.wikipedia.org/wiki/Wikipedia_en_espa%C3%B1ol",
    "https://www.disneyplus.com/es-es",
    "https://support.microsoft.com/es-es",
    "https://drive.google.com/drive/home",
    "https://www.google.com/intl/es/gmail/about/",
    "https://www.max.com/es/en/shows/house-of-the-dragon/c68e69d7-9317-428a-a615-cdf8fe5a2e06",
    "https://www3.animeflv.net/",
    "https://jkanime.net/",
    "https://www.netflix.com/es/",
    "https://store.steampowered.com/?l=spanish",
    "https://www.amazon.es/stores/Xiaomi/REDMINOTE135G_REDMI/page/1DE2888D-4FE4-477B-8E1F-D826202C3B4C",
    "https://earth.google.com/web/",
    "https://www.zara.com/es/",
    "https://www.apple.com/es/app-store/",
    "https://www.mi.com/es/store?utm_campaign=micom_es_brand_0409&utm_source=google&utm_medium=paid-search&utm_type=1&utm_channel=search&utm_content=responstore&gad_source=1&gclid=CjwKCAjw2dG1BhB4EiwA998cqIlh-5oynkkNgcnB0we2-WhEhYO_yVpjOiKKKtOb_wi_KWZ0SaggnRoCmhsQAvD_BwE",
    "https://www.bmw.es/es/home.html",
    "https://www.seat.es/ofertas/coches-nuevos.html?idcmp=sea:10017750_BR_AO_NU_CNV_BRA_BRA_BRD_ESP_NU_SEAH_PSEAC_TEAD_NU_SA3_GOBI_CPC_NU_NU_NU_NU_CXD_ES_EX_PURB_10-BRAND-Exact-10041082:GOOGLE:SEAT:seat:NA:NA:seat&dns=true&ds_rl=1161015&ds_rl=1172071&ds_rl=1176144&gad_source=1&gclid=CjwKCAjw2dG1BhB4EiwA998cqHWdu_k7BSviNFx0BhjZi80QVdAxqNHnEaTYYLqCHLcJsj2ycwY1exoCkM8QAvD_BwE&gclsrc=aw.ds",
    "https://es.wallapop.com/",
    "https://www.milanuncios.com/",
    "https://forocoches.com/foro/forumdisplay.php?f=90",
    "https://sede.agenciatributaria.gob.es/"
    "https://www.uc3m.es/grado/informatica",
    "https://scholar.google.es/scholar?hl=es&as_sdt=0%2C5&q=ciberseguridad&btnG=&oq=ciberseguridad",
    "https://www.google.com/search?channel=fs&client=ubuntu-sn&q=google+academic",
    "https://www.fotocasa.es/es/alquiler/viviendas/espana/todas-las-zonas/l",
    "https://eespa.cancilleria.gob.ar/",
    "https://www.tesla.com/es_es",
    "https://www.binance.com/es",
    "https://www.python.org/",
    "https://www.jetbrains.com/es-es/pycharm/",
    "https://www.virtualbox.org/",
    "http://www.parroquiavisitacion.com/",
    "https://www.patrimonionacional.es/visita/real-monasterio-de-san-lorenzo-de-el-escorial",
    "https://www.realmadrid.com/es-ES",
    "https://alexcordobes.es/",
    "https://www.pp.es/",
    "https://www.psoe.es/",
    "https://electocracia.com/",
    "https://elkiosko.es/",
    "https://elranchodesantaafrica.es/",
    "https://www.imperial.ac.uk/",
    "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.imperial.ac.uk%2Fvisit%2Fcampuses%2F&psig=AOvVaw2YMxTG5Hhs9bNOeaL6Z1LH&ust=1723260034818000&source=images&cd=vfe&opi=89978449&ved=0CBEQjRxqFwoTCIi804T65ocDFQAAAAAdAAAAABAE",
    "https://crossfitcentury.es/",
    "https://www.atptour.com/es/players/rafael-nadal/n409/overview",
    "https://www.coches.net/",
    "https://boardgamegeek.com/boardgame/132018/churchill",
    "https://www.coldplay.com/",
    "https://www.ticketmaster.es/?utm_source=TM-google&utm_medium=cpc&utm_campaign=co:ES+%7C+an:Pure+Brand+%7C+obj:Sales+%7C+chl:Gb+%7C+cat:Branded+%7C+bud:TM+%7C+a:B1+%7C+tp:TMES+%7C+pn:+%7C+p:+%7C+ag:+%7C+fc:Manual+%7C+lc:ES&utm_content=paid&awtrc=true&utm_source=TM-google&camefrom=%7B%7Bcampaign.name%7D%7D&awtrc=true&gad_source=1&gclid=CjwKCAjw2dG1BhB4EiwA998cqEzLojynuiWJpYKo-3aA4jWz3OKJcQkU9SCnFyO-NYV1xNBg8KNyQxoCxLkQAvD_BwE&gclsrc=aw.ds",
    "https://www.catawiki.com/es/c/165-monedas-y-sellos",
    "https://www.mercadolivre.com.br/#from=homecom",
    "https://pacha.com/es",
    "https://www.airbnb.es/a/stays/baiona--espa%C3%B1a?&c=.pi0.pk608529337_81124426271&localized_ghost=true&gad_source=1&gclid=CjwKCAjw2dG1BhB4EiwA998cqFRr5OUNGzWuDNCOBnzhUlcYmxTQfMGL2Zz54zlAN2R2aovwmkS9bBoC8o0QAvD_BwE&gclsrc=aw.ds",
    "https://www.booking.com/index.es.html?aid=2311236;label=es-es-booking-desktop-onknyt5TBrS8m9RnGd*6fgS652829001115:pl:ta:p1:p2:ac:ap:neg:fi:tikwd-65526620:lp9196430:li:dec:dm;ws=&gclid=CjwKCAjw2dG1BhB4EiwA998cqMmLP7Am0zVBxJgduqVp-kj6Wr0taVCf-0X_YhGRAjUgfycjqy-AcxoCIfcQAvD_BwE",
    "https://www.bet365.es/hub/es-es/open-account-offer?affiliate=365_01435657&gclid=CjwKCAjw2dG1BhB4EiwA998cqDxU3-_-WJX77VR5nI5tNz7om0O3oEuHxAx1pAPrlT_tPhCedsKoIxoCD1sQAvD_BwE",
    "https://sports.williamhill.es/betting/es-es",
    "https://www.museodelprado.es/",
    "https://www.correos.es/es/es/particulares",
    "https://olympics.com/es/paris-2024",
    "http://es.china-embassy.gov.cn/esp/",
    "https://spanien.um.dk/es",
    "https://es.usembassy.gov/es/",
    "https://www.ccn-cert.cni.es/es/guias.html",
    "https://www.nqa.com/es-es/certification/standards/iso-27701",
    "https://www.esa.int/Space_in_Member_States/Spain",
    "https://www.nasa.gov/",
    "https://www.movistar.es/",
    "https://www.digimobil.es/combina-telefonia-internet?fibra=1406&movil=1435&gad_source=1&gclid=CjwKCAjw2dG1BhB4EiwA998cqC79sSX-788xPzdpAV1oybG2_Tyc-5WYPg89un4wN8pJG4My0KqiGhoC6eMQAvD_BwE",
    "https://basalorecosm.com/",
    "https://www.uber.com/es/en/ride/?ad_id=694780381344&adg_id=148286515864&campaign_id=18388070762&cre=694780381344&dev=c&dev_m=&fi_id=&gad_source=1&gclid=CjwKCAjw2dG1BhB4EiwA998cqD_6srgsunUpfmEZwxSQy9ozv-5XMv24wn7m5sdEr0ZSf3SrEkT9ZRoC6k8QAvD_BwE&gclsrc=aw.ds&kw=uber&kwid=kwd-12633382&match=b&net=g&placement=&tar=&utm_campaign=CM2215725-search-google-brand_162_-99_ES-National_r_web_acq_cpc_es_T1_Generic_BM_uber_kwd-12633382_694780381344_148286515864_b_c&utm_source=AdWords_Brand",
    "https://www.mutua.es/",
    "https://mcdonalds.es/",
    "https://www.caritas.es/",
    "https://www.defensa.gob.es/",
    "https://playdede.eu/",
    "https://www.lasrozas.es/",
    "https://www.comunidad.madrid/hospital/gregoriomaranon/",
    "https://asociacionestima.org/tca/arfid/",
    "https://www.renfe.com/es/es",
    "https://www.renfe.com/es/es",
    "https://www.iberia.com/es/?cq_src=google_ads&cq_cmp=206334386&cq_con=11273681546&cq_term=iberia&cq_med=&cq_plac=&cq_net=g&cq_plt=gp&esl-k=google-ads|ng|c551271674630|me|kiberia|p|t|dc|a11273681546|g206334386&gad_source=1&gclid=CjwKCAjw2dG1BhB4EiwA998cqNq_Qt8TlaOB6i85bVALn61KaADSfvGwcYSh4C0yajnVJkDvHhV57hoC5YAQAvD_BwE",
    "https://amadeus.com/es",
    "https://www.ryanair.com/es/es",
    "https://www.alten.es/",
    "https://gmv.com/en-es",
    "https://www.uned.es/universidad/inicio/en/",
    "https://flyingtiger.com/es-es?gad_source=1&gclid=CjwKCAjw2dG1BhB4EiwA998cqGHvsKbFqAehVKr_gfbnPCRONUaiBW5M8tVoFd9aC_aRoUU-iic_AxoCCF0QAvD_BwE",
    "https://www.revolut.com/es-ES/",
    "https://www.bbva.es/personas.html",
    "https://www.bancosantander.es/particulares",
    "https://www.flixbus.es/"
    "https://lavacentre.is/",
    "https://www.moralmachine.net/hl/es",
    "https://www.nationalgeographic.com.es/",
    # Añadir más URLs aquí
]

def save_results_to_yaml(results, filename='results.yaml'):
    import yaml
    with open(filename, 'w') as file:
        yaml.dump(results, file, default_flow_style=False)
